services:
  backend:
    build:
      context: ./LMS-Backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./LMS-Backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: ./LMS-Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./LMS-Frontend:/app
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
